version: 3.9'

services:
  service1:
    build: .
    container_name: node_app
    depends_on:
      - service2
    ports:
      - '5000:5000'
    volumes:
      - .:/app

  service2:
    image: 'postgres:latest'
    container_name: db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: 'mysecretpassword'
      POSTGRES_USER: 'oklabs'




